### PR TITLE
Primitive casts are not considered essential.

### PR DESCRIPTION
**Pull request by Lex999**
During execution of dead assignment elimination, primitive casts are not essential because they cannot throw any exceptions.

### CODE REVIEW

**Comment by mbenz89** [comment]
Could you elaborate this fix a bit more, please? An example where the old code breaks would be very helpful.

**Comment by Lex999** [comment]
Consider the following Jimple code:
```
public static int myMethod(int, int)
{
   int a, b, c;
   double d;
   a = @parameter0: int;
   b = @parameter1: int;
   c = a + b;
   d = (double) a;
   return c;
}
```
The old code would not eliminate the assignment to d because "double" is no ReferenceType. As primitive type casts cannot throw any exceptions, they can be removed without modifying behaviour when the result is not used. The new code will remove the assignment to d.

After thinking about it, "RefType" in the modified code line should probably replaced by "RefLikeType" to catch casts to an ArrayType.

**Comment by mbenz89** [comment]
I see. Thanks for your explanation!
Could you add a test case for the fix? This would greatly help to understand the feature and keep it robust against future changes which.

> After thinking about it, "RefType" in the modified code line should probably replaced by "RefLikeType" to catch casts to an ArrayType.

Good point. Could you change that as well?

**Comment by ericbodden** [comment]
@Lex999 are you planning any updates on this? We'd be happy to merge it once completed.

**Comment by Lex999** [comment]
I'm going to write a test and make the type check correct. It will take a week or two.

**Comment by mbenz89** [comment]
Great! Thank you for your efforts!

Lex999 <notifications@github.com> schrieb am Sa., 29. Feb. 2020, 16:26:

**Comment by Lex999** [comment]
OK. Now, it should be ready for merge.

**Pull request merged**
