### PR TITLE
Fix for issue #814:

### PR DESCRIPTION
**Pull request by jpstotz**
The AndroidManifest.xml parser has been replaced by axml

### CODE REVIEW

**Comment by jpstotz** [comment]
Note this pull request uses a new axml library. The library can be found here: https://github.com/jpstotz/soot-axml
I would recommend to fork/move it into the Github Soot namespace

**Comment by mbenz89** [comment]
Can one of the admins verify this patch?

**Comment by mbenz89** [comment]
ok to test

**Comment by mbenz89** [comment]
Build finished.

**Comment by jpstotz** [comment]
Steven just talked to me that they have prepared a similar patch.

**Comment by mbenz89** [comment]
Thanks for your the contribution anyway! I'll close this pr.

**Comment by mbenz89** [comment]
Fixed in 3e8dced9e5f669a7a247a6ef4ecc6bc7b459da97

**Pull request closed without merging**
