### PR TITLE
Adding support for output_jar flag

### PR DESCRIPTION
**Pull request by pnest**
* Made DexPrinter write to jar file when source APK is absent. To enable it set `Options.v().set_output_jar(true)`
* replaced manual closing streams with try with resources
* replaced writing to System out with slf4j logger

### CODE REVIEW

**Comment by mbenz89** [comment]
ok to test

**Comment by mbenz89** [comment]
@pnest Would you mind adding some additional information on how the `set_output_jar` option changes output semantics when analyzing an apk to the soot_options.xml?

**Comment by StevenArzt** [comment]
@pnest Any news on the merge request?

**Comment by pnest** [comment]
Added usage notes to ``soot_options.xml`` and also updated ``.xls`` files to generate clearer ``.java`` classes - will definitely need this done when code formatting checker will be applied

**Comment by mbenz89** [comment]
Thanks for your contribution! 
Btw. we are not planning to check the formatting of generated files. These should have a consistent formatting anyway.

**Comment by StevenArzt** [comment]
Please do not reduce the visibility of fields or methods. If something is protected, there may be code that depends on being able to access the respective member through a subclass. I'll change the affected members back to protected.

**Pull request merged**
