### PR TITLE
WIP: Add support for invoke-polymorphic and invoke-custom in dex and fix some issues with normal invoke-dynamic

### PR DESCRIPTION
**Pull request by agorski3**
Explanation is in the commit messages

### CODE REVIEW

**Comment by agorski3** [comment]
Ok so apparently there are a few dependencies on changes I made to dexlib2 that I forgot about. This means these soot changes depend on the most up to date version of dexlib2 from the git repo (once he accepts my pull request). Not sure how you will work that though since everything is pulled from maven.

**Comment by mbenz89** [comment]
Okay, please keep me updated on the status of your pr to dexlib2.

**Comment by agorski3** [comment]
Dexlib2 has finally been updated to include my pull request but he has not released a new version yet with the changes. It is not clear when he will do that either. However, it is in the repo so it can be pulled and built manually.

**Comment by mbenz89** [comment]
Thanks for letting me know! 
If this feature is requested by Soot users a lot, it might make sense to build and deploy dexlib2 our selves. Since this is currently not the case, I would rather wait for a stable release of dexlib2 before merging.

Thanks for your efforts, the pr looks quite nice!

**Comment by agorski3** [comment]
No problem. I will let you know once he releases a new version.

**Comment by StevenArzt** [comment]
@mbenz89 Can you please double-check whether the 2.2.5 release of Dexlib is new enough to finally accept this merge request? It has been a while since this MR was updated and we should integrate it before it gets fully outdated.

**Comment by agorski3** [comment]
The 2.2.5 release of Dexlib 2 is available now and it has the changes I made to make my code here work. Sorry it was apparently released back at the beginning of Sep. I just have been busy with a seperate project and haven't checked since then.

**Comment by StevenArzt** [comment]
That means we now need to get the MR fixed (most likely incompatibilities due to changes to the code base in the meantime) and are then ready to merge, right?

**Comment by agorski3** [comment]
Yes it was ready for merging back when I made the pr. The dexlib2 version just needs to be bumped up to 2.2.5 and then whatever changes in the code base were made need to be accounted for.

**Comment by StevenArzt** [comment]
@mbenz89 Can you have a look at this?

**Comment by mbenz89** [comment]
@StevenArzt Sure, I'll finish this up on Monday.
@agorski3 Thanks for keeping us updated!

**Comment by mbenz89** [comment]
I've raised the dexlib2 dependency to 2.2.5 and added some very basic test cases in #1047.

The PR looks good so far. However, since `invokeCustom` calls are transformed to Soot's `JDynamicInvokeExpr`, we will break when writing back out code using `invokeCustom`. This happens since we do not handle `invokeDynamic` for dex write-out at all:  https://github.com/Sable/soot/blob/develop/src/main/java/soot/toDex/ExprVisitor.java#L154

@StevenArzt Should we still merge this PR now and open a new issue for write-out support, or try to get this completed first?
@agorski3 Would you be able to implement such a write-out support? It should be sufficient to transform `invokdeDynamic` statments back to `invokeCustom`.

Regarding write-out of `invokePolymorphic` statments, as far as I undestand, we only loose the prototype when transforming these to `invokeVirtual`. Thus, using `invokeVirtual` instead of `invokePolymorphic` on write-out should still keep the code executable. Is that correct, @agorski3 ?

**Comment by StevenArzt** [comment]
@mbenz89 At the moment, we do not support ```invokeCustom``` at all. Attempts to read in an apps that contains such code will either fail or deliver incomplete Jimple code. Neither possibility will result in a working app after writeout. Thus, we'll not make anything worse when adding support for reading in such constructs. So let's go ahead and add the write-out support later.

**Comment by agorski3** [comment]
I second the idea of worrying about writing out invokeCustom later. It was not required for what I was doing (just need to read in dex code with invokePolymorphic or invokeCustom) so I have not written any code to write it out and don't really have time to tackle it at the moment. As for invokePolymorphic since it it transformed into an invokeVirtual you are correct in assuming that there should be no issue with writing this stmt back and still having the code execute.

**Comment by mbenz89** [comment]
I agree. Thanks again for your contribution, @agorski3 .

**Comment by mbenz89** [comment]
Merged by #1047

**Pull request merged**
