### PR TITLE
Clarify semantics of Chain.follows

### PR DESCRIPTION
**Pull request by MarcMil**

### CODE REVIEW

**Comment by mbenz89** [comment]
Wouldn't it make sense to fix the implementation? It sounds very counterintuitive as it currently is which is also represented by the required documentation.

**Comment by MarcMil** [comment]
I'd like to do that as well, but what about existing implementations which may depend on the current implementation's behavior?

**Comment by mbenz89** [comment]
Are you aware of any such implementations? I would rather guess that people using the API expect it to behave as the previous documentation stated.
There seem to be only two uses in the Soot codebase. Maybe you have a look at those and potential usages in FlowDroid.

Anyway, I don't think we should keep strange things like this for "backward compatibility". We will issue a new release soon and if people do not want to adapt to the changes, they are free to stick to an older version.

**Comment by MarcMil** [comment]
I've changed the implementation. Should be consistent now.

**Comment by mbenz89** [comment]
Thanks for that! Have you checked the usages in Soot for correctness?

**Comment by MarcMil** [comment]
It should be fine, as no different units from different methods should be part of the follows call at these two call sites.

**Comment by mbenz89** [comment]
Perfect, thanks!

**Pull request merged**
