### PR TITLE
Add CuckooHashMap to .get() hotspots.

### PR DESCRIPTION
**Pull request by GUIpsp**
Before this can be merged a cuckoo hash map implementation needs to be added. The one I used in my testing is Apache 2.

### CODE REVIEW

**Comment by StevenArzt** [comment]
Do you have numbers on how and whether this improves Performance?

**Comment by GUIpsp** [comment]
How this improves performance? Cuckoo hash maps provide O(1) .get()

I don't have the numbers but as with my other optimizations, these are guided by profiling the application.

Without this optimization+ #427 it took me 18 minutes to class->shimple my data. With these optimizations it takes me 10 minutes.

**Comment by nignag** [comment]
As the default JDK implementation of the Maps performs really well. I don't believe this request would change anything beyond introducing new map-class. if "get" is really a hotspot, than you changing the initial hashmap size should be enough. If it is not helping find out why "get" is a really hotspot

**Comment by GUIpsp** [comment]
> I don't believe this request would change anything beyond introducing a new map-class.

But it did. 

> if "get" is really a hotspot, than changing the initial hashmap size should be enough.

This only works when you know the expected size, and even then, collisions will happen, unless you set the doubling threshold insanely low.

> If it isn't helping, find out why "get" is a really hotspot

It's a hotspot because the maps are being used as they are supposed to. We just need faster gets.

> As the default JDK implementation of the Maps performs really well.

Good. But this one performs better.

**Comment by GUIpsp** [comment]
We already use apache 2 libs. Can we use an apache 2 Map implementation?

**Comment by GUIpsp** [comment]
@StevenArzt

**Comment by StevenArzt** [comment]
In general, we can switch to a different map implementation. To do so, we however need good evidence that it really buys us something and we would need to carefully check where in Soot to use the new list and where to stick with the old one (and why). This is nothing I want to do in the passing.

**Pull request closed without merging**
