### PR TITLE
Bugfix in ArrayPackedSet.toList / SimpleDominatorsFinder

### PR DESCRIPTION
**Pull request by nignag**
missing first element

### CODE REVIEW

**Comment by GUIpsp** [comment]
This does not compile for me:

    Error:(95, 32) java: cannot find symbol
      symbol:   variable analysis
      location: class soot.toolkits.graph.SimpleDominatorsFinder<N>

**Comment by nignag** [comment]
@GUIpsp thx

**Comment by StevenArzt** [comment]
@nignag Soot does not compile anymore because the method FlowUniverse.complement() is missing, but used in SimpleDominatorsAnalysis.java in line 144. Can you double-check this?

**Comment by StevenArzt** [comment]
@nignag I fixed it, never mind.

**Pull request merged**
