### PR TITLE
Adding supports for dealing with android.os.Handler.sendxxxxMessagexxxx and android.os.Handler.handleMessage(android.os.Message)

### PR DESCRIPTION
**Pull request by njupt-moon**

### CODE REVIEW

**Comment by mbenz89** [comment]
Hi.

Thanks for your contribution! Can you provide a minimal example app, where your changes help to make the call graph more complete?

Manuel

**Comment by njupt-moon** [comment]
A demo and the corresponding description can be found here: https://gist.github.com/njupt-moon/a59a9e7f59658e533b0d2dbf35a5d13c. The test is performed based on Flowdroid. Thanks!

BTW: there is a mistake in line 750 of the uploaded OnFlyCallGraphBuilder.java. "addVirtualCallSite(true, s, m, receiver, iie, sigHandlerHandleMessage, Kind.HANDLER);" should be changed to "addVirtualCallSite(s, m, receiver, iie, sigHandlerHandleMessage, Kind.HANDLER);". Thanks.

**Comment by StevenArzt** [comment]
@njupt-moon Can you fix that mistake so that we can merge your request?

**Comment by njupt-moon** [comment]
@StevenArzt 
I have pulled a patch to fix the mistake, and here is the request link: https://github.com/Sable/soot/pull/815. Thanks.

**Comment by StevenArzt** [comment]
merged by hand.

**Pull request closed without merging**
