### PR TITLE
Update FastHierarchy

### PR DESCRIPTION
**Pull request by pavanupb**
Added logic to take child method signature in the hierarchy

### CODE REVIEW

**Comment by mbenz89** [comment]
@pavanupb Please fix the style issue.

**Comment by pavanupb** [comment]
> @pavanupb Please fix the style issue.

@mbenz89 How to fix style issue?. I was not able to get it.

**Comment by mbenz89** [comment]
You can click on details besides the StyleCheck item that failed and then console log:
https://soot-build.cs.uni-paderborn.de/jenkins/job/soot/job/soot-pr-checkstyle/236/console

There is a list of failed checks. You can also just manually execute the stylecheck by invoking `mvn verify`

**Comment by pavanupb** [comment]
> You can click on details besides the StyleCheck item that failed and then console log:
> https://soot-build.cs.uni-paderborn.de/jenkins/job/soot/job/soot-pr-checkstyle/236/console
> 
> There is a list of failed checks. You can also just manually execute the stylecheck by invoking `mvn verify`

I am getting the following test failures:
[ERROR]   EnumTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line private final static synthetic [Lsoot/asm/backend/targets/MyEnum; $VALUES, but got private final static synthetic [Lsoot/asm/backend/targets/MyEnum; ENUM$VALUES in line 16 for class soot.asm.backend.targets.MyEnum
[ERROR]   ExtendedArithmeticLibTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line L0, but got GOTO L0 in line 103 for class soot.asm.backend.targets.ExtendedArithmeticLib
[ERROR]   InstanceOfCastsTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line CHECKCAST [Lsoot/asm/backend/targets/Measurable;, but got ARETURN in line 22 for class soot.asm.backend.targets.InstanceOfCasts
[ERROR]   ModifiersTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line // access flags 0x902, but got // access flags 0x102 in line 60 for class soot.asm.backend.targets.Modifiers
[ERROR]   MonitorTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable, but got ALOAD 0 in line 20 for class soot.asm.backend.targets.Monitor
[ERROR]   StoresTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line INVOKESPECIAL java/lang/StringBuilder.<init> ()V, but got LDC 2343249 in line 40 for class soot.asm.backend.targets.Stores
[ERROR]   TryCatchTest>AbstractASMBackendTest.runTestAndCompareOutput:131 Expected line TRYCATCHBLOCK L0 L1 L3 java/lang/Throwable, but got TRYCATCHBLOCK L0 L3 L4 java/lang/Throwable in line 18 for class soot.asm.backend.targets.TryCatch
[ERROR]   DexByteCodeInstrutionsTest.InvokeCustom1:105->AbstractTestingFramework.prepareTarget:94->AbstractTestingFramework.prepareTarget:112->AbstractTestingFramework.setupSoot:152->setupSoot:62->targetDexPath:81 NullPointer
[ERROR]   DexByteCodeInstrutionsTest.InvokePolymorphic1:89->AbstractTestingFramework.prepareTarget:94->AbstractTestingFramework.prepareTarget:112->AbstractTestingFramework.setupSoot:152->setupSoot:62->targetDexPath:81 NullPointer

Should I go ahead and fix them?

**Comment by mbenz89** [comment]
Already merged

**Pull request closed without merging**
