### PR TITLE
Added processing of multiple DEX files in an APK

### PR DESCRIPTION
**Pull request by vitaliiavdiienko**
Hi @StevenArzt and @ericbodden,

there is my solution for the issue that we discussed in #565.

Maybe not the best one but can be helpful :smile: 

Best Regards,
Vitalii

### CODE REVIEW

**Comment by StevenArzt** [comment]
Please add an option to make this behavior optional. As I wrote in the other thread, there are multiple ways in which this can break existing analyses and software. I agree that it is helpful in some cases, but not in all of them. One such example where we are dependent on the old behavior is, for instance, a fuzzing-based approach we are currently working on where we only want to merge what is on the current trace.

**Comment by vitaliiavdiienko** [comment]
Please check my last commit.

**Comment by ericbodden** [comment]
@vitaliiavdiienko Thanks for this. Could you still please add a few comments to the code (where suitable)?

Also, very importantly, Soot options should only be added by modifying soot-options.xml. Our build script then generates the required options code automatically.

**Comment by StevenArzt** [comment]
Yes, that's one final important point. Add new options to options.xml and have the ant build script re-generate the code files and documentation accordingly. Otherwise, your changes will be overwritten during our automatic builds. Thanks a lot for your contribution!

**Comment by vitaliiavdiienko** [comment]
Thanks! I have just learned the correct way of adding options. Here we go 53057c7f6cd615086dade582489035d01612359f

**Pull request merged**
